---
name: Auto Semver
on:
  pull_request:
    types: closed
    branches:
      - main
jobs:
  update:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Run Auto Semver
        uses: discoverygarden/auto-semver@v1
